package com.example.kalkulator;/*
 * @project Kalkulator
 * @author kola
 */

import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.testfx.api.FxRobot;
import org.testfx.framework.junit5.ApplicationExtension;
import org.testfx.framework.junit5.ApplicationTest;
import org.testfx.framework.junit5.Start;

import java.util.Objects;

@ExtendWith(ApplicationExtension.class)
public class dzialaniaCalkaTest extends ApplicationTest {
    public double x, y;

    @Start
    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(Objects.requireNonNull(dzialaniaCalkaTest.class.getResource("fxml/Home.fxml")));

        root.setOnMousePressed(event -> {
            x = stage.getX() - event.getSceneX();
            y = stage.getY() - event.getSceneY();
        });

        root.setOnMouseDragged(event -> {
            stage.setX(event.getSceneX() + x);
            stage.setY(event.getSceneY() + y);
        });

        stage.setScene(new Scene(root, 606, 614));
        stage.toFront();
        stage.show();
    }

    @Test
    public void dzialaniaCalka(FxRobot robot){
        robot.clickOn("#kCalek");
        robot.sleep(2000);

        robot.clickOn("#menu");
        robot.sleep(500);
        robot.clickOn("#jednostkaChoiceBox");
        robot.clickOn("Radiany");

        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#nawiasLID");
        robot.clickOn("#eID");
        robot.clickOn("#razyID");
        robot.clickOn("#piecOnAction");
        robot.clickOn("#silniaID");
        robot.clickOn("#nawiasPID");
        robot.clickOn("#minusID");
        robot.clickOn("#sinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#piID");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#pier2ID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write(",12]");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#pier2ID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write(",15]");
        robot.clickOn("#liczbaPodprzedzialow");
        robot.clickOn("#piecOnAction");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#szescOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z niedomiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda trapezów");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda Simpsona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda analityczna");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Całka nieoznaczona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");

        robot.clickOn("#usunID");

//FUNKCJE TRYGONOMETRYCZNE
        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#sinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#cosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#sinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#granicaGorna").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#sinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#granicaDolna").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#tanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#cotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#cosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("2]");
        robot.clickOn("#minusID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#cosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("0]");
        robot.clickOn("#minusID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#tanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#cotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#tanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("3]");
        robot.clickOn("#razyID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#tanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("5]");
        robot.clickOn("#razyID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#tanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#cotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#cotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("10]");
        robot.clickOn("#dzielID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#cotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("1]");
        robot.clickOn("#dzielID");
        robot.clickOn("#siedemOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.sleep(1000);

//FUNKCJE CYKLOMETRYCZNE
        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#asinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#acosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#asinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#granicaGorna").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#asinID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#jedenOnAction");
        robot.clickOn("#granicaDolna").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#jedenOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#atanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#acotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#acosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("1]");
        robot.clickOn("#minusID");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#acosID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("0]");
        robot.clickOn("#minusID");
        robot.clickOn("#siedemOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#atanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#acotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]+xk");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#atanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("1]");
        robot.clickOn("#razyID");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#atanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("0]");
        robot.clickOn("#razyID");
        robot.clickOn("#siedemOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z niedomiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda trapezów");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda Simpsona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda analityczna");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Całka nieoznaczona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");

        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#usunOstatnieID");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z niedomiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda trapezów");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda Simpsona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda analityczna");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Całka nieoznaczona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");

        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#jednostkaChoiceBox");
        robot.clickOn("Stopnie");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#atanID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#dwaOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#plusID");
        robot.clickOn("#acotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#zeroOnAction");
        robot.clickOn("#kropkaID");
        robot.clickOn("#trzyOnAction");
        robot.clickOn("#wpisanaCalka").write("]");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#acotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaGorna").write("0]");
        robot.clickOn("#dzielID");
        robot.clickOn("#siedemOnAction");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#acotID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#usunOstatnieID");
        robot.clickOn("#granicaDolna").write("1]");
        robot.clickOn("#dzielID");
        robot.clickOn("#siedemOnAction");

        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z niedomiarem");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda trapezów");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda Simpsona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda analityczna");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Całka nieoznaczona");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#metodaChoiceBox");
        robot.clickOn("Metoda prostokątów z nadmiarem");
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka").write("tan[π]");
        robot.clickOn("#granicaGorna").write("10");
        robot.clickOn("#granicaDolna").write("2");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#liczbaPodprzedzialow").write("4");
        robot.clickOn("#wpisanaCalka").write("tan[22]");
        robot.clickOn("#granicaGorna").write("10");
        robot.clickOn("#granicaDolna").write("2");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
        robot.clickOn("#usunID");

        robot.clickOn("#usunID");
        robot.clickOn("#wpisanaCalka");
        robot.clickOn("#xID");
        robot.clickOn("#dzielID");
        robot.clickOn("#osiemOnAction");
        robot.clickOn("#dziewiecOnAction");
        robot.clickOn("#plusID");
        robot.clickOn("#szescOnAction");
        robot.clickOn("#granicaGorna");
        robot.clickOn("#piecOnAction");
        robot.clickOn("#szescOnAction");
        robot.clickOn("#plusID");
        robot.clickOn("#nawiasLID");
        robot.clickOn("#piID");
        robot.clickOn("#plusID");
        robot.clickOn("#osiemOnAction");
        robot.clickOn("#silniaID");
        robot.clickOn("#nawiasPID");
        robot.clickOn("#plusID");
        robot.clickOn("#dziewiecOnAction");
        robot.clickOn("#plusID");
        robot.clickOn("#xID");
        robot.clickOn("#granicaDolna");
        robot.clickOn("#szescOnAction");
        robot.clickOn("#piecOnAction");
        robot.clickOn("#plusID");
        robot.clickOn("#nawiasLID");
        robot.clickOn("#piID");
        robot.clickOn("#plusID");
        robot.clickOn("#osiemOnAction");
        robot.clickOn("#silniaID");
        robot.clickOn("#nawiasPID");
        robot.clickOn("#plusID");
        robot.clickOn("#dziewiecOnAction");
        robot.clickOn("#plusID");
        robot.clickOn("#xID");
        robot.clickOn("#liczbaPodprzedzialow");
        robot.clickOn("#dziewiecOnAction");
        robot.clickOn("#osiemOnAction");
        robot.clickOn("#wynikID");
        robot.sleep(3000);
    }
}
